version: '2'

services:
  db:
    image: postgres
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=octoberry_production
      - DATABASE_USERNAME=octoberry
      - DATABASE_PASSWORD=octoberry
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  api:
    build: .
    command: gunicorn -w 4 main:app --bind 0.0.0.0:8000 --worker-class aiohttp.worker.GunicornWebWorker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=octoberry_production
      - DATABASE_USERNAME=octoberry
      - DATABASE_PASSWORD=octoberry

networks:
  default:
    external:
      name: testoctoberry