#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    DROP DATABASE IF EXISTS ${DATABASE_NAME};
    DROP ROLE IF EXISTS ${DATABASE_USERNAME};
    CREATE USER ${DATABASE_USERNAME} WITH PASSWORD '${DATABASE_PASSWORD}';
    CREATE DATABASE ${DATABASE_NAME} ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USERNAME};
EOSQL