"""article_id for comment

Revision ID: 42265a48bfcd
Revises: 8e102708968f
Create Date: 2017-08-23 09:08:50.715946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42265a48bfcd'
down_revision = '8e102708968f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('article_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'article_id')
    # ### end Alembic commands ###
